name: Daily Trivia RSS Update

on:
  schedule:
    - cron: '0 9 * * *' # Runs at 5:00 AM Eastern (9 AM UTC)
  workflow_dispatch: # allows manual trigger if needed

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install feedgen
        run: pip install feedgen

      - name: Generate new RSS feed
        run: |
          python update_feed.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.xml
          git commit -m "🔄 Auto-update RSS feed"
          git push
